- command: pwd
  register: pwd
  tags:
  - build
  - stop
  - start
  - test
- name: make all
  docker_image:
      state: present
      docker_api_version: 1.18
      name: "{{ item.name }}"
      dockerfile: build/test/{{ item.name }}.Dockerfile
      path: "{{ pwd.stdout }}"
      force: true
      rm: false
  with_items: "{{ images }}"
  tags: 
  - build

- name: stop all
  docker:
      name: "{{ item.name }}"
      docker_api_version: 1.18
      state: stopped
      image: "{{ item.name }}"
      stop_timeout: 2
  with_items: "{{ images }}"
  tags:
  - stop

- name: start all
  docker_container: 
      name: "{{ item.name }}"
      image: "{{ item.name }}"
      docker_api_version: 1.18
      state: started
      network_mode: bridge
      recreate: true
      restart: true
      published_ports: "{{ item.ports }}"
      links: "{{ item.links  }}"
      volumes: "{{ item.volumes }}"
  with_items: "{{ images }}"
  tags: 
  - start
- name: workaround to get gondul-varnish-front-ip
  shell: "docker inspect gondul-varnish-test | grep IPAddress | sed 's/[^0-9.]//g' | grep 172.17 | uniq"
  register: ip
  tags:
  - start
  - test
- name: workaround to get gondul-front-ip
  shell: "docker inspect gondul-front-test | grep IPAddress | sed 's/[^0-9.]//g' | grep 172.17 | uniq"
  register: ipfront
  tags:
  - start
  - test

- name: Display IP
  tags:
  - start
  - test
  debug:
    msg: "Varnish test is available at http://{{ ip.stdout }}/ uncached ip: http://{{ ipfront.stdout }}/ "

