---
- hosts: all
  vars:
    git_repo: https://github.com/gathering/gondul.git
    git_branch: master
  become: true
  roles:
    - common
    - postgres
    - web
    - influx
    - ping
    - snmp
  tasks:
    - name: "download/replace pics"
      get_url:
        url: https://raw.githubusercontent.com/ZnarreZ/gondul/master/web/img/floor.png
        dest: /opt/gondul/web/pic/floor.png
        force: true
